apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  claimRef:
    name: redis01-pvc
    namespace: default
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redis01"
