apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  selector:
    app: redis-cluster
  ports:
    - protocol: TCP
      port: 6379
      name: client
      targetPort: 6379
    - protocol: TCP
      port: 16379
      name: gossip
      targetPort: 16379
