apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  claimRef:
    name: data-pvc
    namespace: default
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/web"